# Generated by Django 4.0 on 2021-12-26 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.ImageField(null=True, upload_to='static/images/')),
                ('dcp', models.ImageField(null=True, upload_to='static/images/')),
                ('original', models.ImageField(null=True, upload_to='static/images/')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ('guid',),
            },
        ),
    ]
