# Generated by Django 3.2.8 on 2021-12-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dehaze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='cep_sharpness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='dcp_sharpness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='original_sharpness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='cep',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='results',
            name='dcp',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='results',
            name='original',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
