# Generated by Django 3.2.8 on 2021-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dehaze', '0002_auto_20211228_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='cep_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='dcp_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='original_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
