export const DATASET_UPLOAD_REQUEST = "DATASET_UPLOAD_REQUEST";
export const DATASET_UPLOAD_SUCCESS = "DATASET_UPLOAD_SUCCESS";
export const DATASET_UPLOAD_FAIL = "DATASET_UPLOAD_FAIL";
export const DATASET_UPLOAD_RESET = "DATASET_UPLOAD_RESET";
