export const GET_RESULT_REQUEST = "GET_RESULT_RESULT";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_FAIL = "GET_RESULT_FAIL";
export const GET_RESULT_RESET = "GET_RESULT_RESET";
