export const UPLOAD_FILE_REQUEST="UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS="UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED="UPLOAD_FILE_FAILED";
export const UPLOAD_FILE_RESET="UPLOAD_FILE_RESET";
